id: IA0011DB7
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-22T17:35:23+00:00'
last_modified: '2022-06-08T05:52:52.374465+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W8LS19090
  title: ཉེས་དོན་བཅའ་ཁྲིམས་བསླབ་དེབ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: true
  base:
    '1100':
      image_group_id: I8LS19092
      title: ''
      total_pages: 548
      order: 1
      base_file: 1100.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
